spring:
  application:
    name: BookManagmentSystem

  datasource:
    url: jdbc:mysql://localhost:3306/book-system
    username: root  # ??? ???????????? ???? ??????
#   password:   # ?????? ???? ??????
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10  # ???????????? ?????????? ?????????? ? ????
      minimum-idle: 5        # ??????????? ?????????? ?????????? ??????????
      idle-timeout: 30000    # ????? ??????? ?????????? ????? ??? ????????? (? ?????????????)
      connection-timeout: 30000  # ????? ???????? ??????????? (? ?????????????)
      max-lifetime: 1800000  # ???????????? ????? ????? ?????????? (? ?????????????)

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true  # ???????? ????? SQL-???????? ? ???????

#  # ????????? OAuth2 ???????
#  security:
#    oauth2:
#      client:
#        registration:
#          cognito:
#            client-id: <YOUR_COGNITO_CLIENT_ID>  # ID ??????? ?? Amazon Cognito
#            client-secret: <YOUR_COGNITO_CLIENT_SECRET>  # ?????? ??????? (???? ???????)
#            scope: openid, email, profile  # ????????????? ??????????
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-name: Amazon Cognito
#        provider:
#          cognito:
#            authorization-uri: https://<YOUR_COGNITO_DOMAIN>.auth.<REGION>.amazoncognito.com/oauth2/authorize
#            token-uri: https://<YOUR_COGNITO_DOMAIN>.auth.<REGION>.amazoncognito.com/oauth2/token
#            user-info-uri: https://<YOUR_COGNITO_DOMAIN>.auth.<REGION>.amazoncognito.com/oauth2/userInfo
#            user-name-attribute: sub
#            jwk-set-uri: https://<YOUR_COGNITO_DOMAIN>.auth.<REGION>.amazoncognito.com/.well-known/jwks.json
#


  # ??????????? (???? ?????)
logging:
  level:
    org.hibernate.SQL: DEBUG  # ??? ??????????? SQL-????????
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # ??? ??????????? ???????? ?????????? ? ????????
